#!/bin/bash
# GitHub CLI 토큰 인증 가이드

echo "🔐 GitHub CLI 토큰 인증 방법"
echo ""
echo "1. 브라우저에서 다음 URL을 엽니다:"
echo "   https://github.com/settings/tokens"
echo ""
echo "2. 'Generate new token' → 'Generate new token (classic)' 클릭"
echo ""
echo "3. 토큰 이름 입력 (예: gh-cli)"
echo ""
echo "4. 다음 권한을 체크하세요:"
echo "   ✅ repo (전체)"
echo "   ✅ read:org (조직 읽기, 필요시)"
echo "   ✅ workflow (GitHub Actions 사용시)"
echo ""
echo "5. 'Generate token' 클릭"
echo ""
echo "6. 생성된 토큰을 복사 (한 번만 보여집니다!)"
echo ""
echo "7. 아래 명령어 실행:"
echo "   gh auth login --with-token < token.txt"
echo "   또는"
echo "   echo 'YOUR_TOKEN_HERE' | gh auth login --with-token"
echo ""
echo "또는 직접 입력:"
echo "   gh auth login"
echo "   → GitHub.com 선택"
echo "   → HTTPS 선택"
echo "   → Yes (Git 인증)"
echo "   → 'Paste an authentication token' 선택"
echo "   → 토큰 붙여넣기"

